apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-k8s-app
  template:
    metadata:
      labels:
        app: go-k8s-app
    spec:
      containers:
        - name: go-k8s-app
          image: jackupsurya/go-k8s-app:v1
          ports:
            - containerPort: 8080
